---
name: Build Titanoboa ISOs
on:
  pull_request:
    branches:
      - main
  schedule:
    - cron: "00 13 1 * *" # 13:00 (1pm) on the 1st of the month
  push:
    paths:
      - "iso_files/**"
      - "flatpaks/**"
  workflow_dispatch:

jobs:
  build:
    name: Build and push ISO file
    runs-on: ubuntu-24.04

    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout the repository
        id: checkout
        uses: actions/checkout@v6

      - name: Maximize build space
        uses: ublue-os/remove-unwanted-software@695eb75bc387dbcd9685a8e72d23439d8686cba6 # v10

      - name: Build ISO
        id: build
        uses: ublue-os/titanoboa@main
        with:
          image-ref: docker pull ghcr.io/sixtyfourhq/halcyon:latest
          flatpaks-list: ${{ github.workspace }}/flatpaks/system-flatpaks.list
          hook-post-rootfs: ${{ github.workspace }}/iso_files/iso_config.sh
          kargs: ""
          builder-distro: fedora
          iso-dest: halcyon.iso

      - name: Rename and Checksum ISO
        id: rename
        run: |
          mkdir -p output
          mv ${{ steps.build.outputs.iso-dest }} output/halcyon.iso
          (cd output && sha256sum halcyon.iso | tee halcyon.iso-CHECKSUM)

      - name: Upload ISO to Job Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: halcyon.iso
          if-no-files-found: error
          path: output/
